(routNormal) @rout_normal
(routNotNum) @rout_normal
(routPunct) @rout_normal
(routWPunct) @rout_normal
(routNumber) @rout_number
(routNegNum) @rout_negnum
(routTrue) @rout_true
(routFalse) @rout_false
(routInf) @rout_inf
